title: Blueprint Scholastic Journalism Conference 2019 | The Phillipian
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "blueprint"
url: ""

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed